[package]
name = "app_data"
version = "0.1.0"
authors = ["Michael Johnson <johnsomor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
mime = "0.3.16"


